{% set name = "pmapper" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pmapper-{{ version }}.tar.gz
  sha256: f59b7922fff7d58002745474e2536ca056aa756d0c6ca96aa272539f67def259

build:
  number: 0
  noarch: python
  entry_points:
    - get_pharm_counts = pmapper.get_pharm_counts:entry_point
    - pmapper_speed_test = pmapper.speedtest.pmapper_speed_test:entry_point
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - rdkit >=2017.09
    - networkx >=2

test:
  imports:
    - pmapper
    - pmapper.speedtest
  commands:
    - pip check
    - get_pharm_counts --help
    - pmapper_speed_test --help
  requires:
    - pip

about:
  home: https://github.com/DrrDom/pmapper
  summary: 'pmapper: 3D pharmacophore hashes and fingerprints'
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
