context:
  name: pmapper
  version: "1.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pmapper-${{ version }}.tar.gz
  sha256: d35734c365b37e06c8246e5efd071b4a314aa978190dce30a147123475e7234f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - get_pharm_counts = pmapper.get_pharm_counts:entry_point
      - pmapper_speed_test = pmapper.speedtest.pmapper_speed_test:entry_point

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - rdkit
    - networkx >2

tests:
  - python:
      imports:
        - pmapper
      python_version: ${{ python_min }}.*
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - get_pharm_counts --help
      - pmapper_speed_test --help

about:
  summary: "pmapper: 3D pharmacophore hashes and fingerprints"
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/DrrDom/pmapper

extra:
  recipe-maintainers:
    - hadim
